server:
  port: 9201
spring:
  application:
    name: zxkj-system
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.25:8848
  redis:
    host: localhost
    port: 6379
    password:
